/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.Carton;
import datos.CatalogoResiduos;
import datos.Gato;
import datos.Organicos;
import datos.Papel;
import datos.Peligrosos;
import datos.Plasticos;
import datos.Residuos;
import datos.Vidrios;
import java.awt.BorderLayout;
import java.awt.Font;
import java.io.Serializable;
import java.util.HashMap;
import javax.swing.ImageIcon;

/**
 *
 * @author TOSHIBA
 */
public class PantallaDeResiduos extends javax.swing.JPanel implements Serializable{

    static CatalogoResiduos catalogoResiduos = new CatalogoResiduos();
    static HashMap<String, Residuos> catalogo = catalogoResiduos.getCatalogo();
    private static int imagenResiduo;
    
        
    public PantallaDeResiduos() {
        initComponents();
        
        ImageIcon atras = new ImageIcon("./src/img/atras.png");
        atras = Pantalla.escalar(atras.getImage(), 50, 50);
        ImageIcon carton = Pantalla.escalar(catalogo.get("Carton").getImagen(),
                130,130);
        ImageIcon ordinarios = Pantalla.escalar(catalogo.get("Ordinarios").getImagen(),
                130,130);
        ImageIcon  organicos = Pantalla.escalar(catalogo.get("Organicos").getImagen(),
                130,130);
        ImageIcon papel = Pantalla.escalar(catalogo.get("Papel").getImagen(),
                130,130);
        ImageIcon peligroso = Pantalla.escalar(catalogo.get("Peligrosos").getImagen(),
                130,130);
        ImageIcon plastico = Pantalla.escalar(catalogo.get("Plasticos").getImagen(),
                130,130);
        ImageIcon vidrio = Pantalla.escalar(catalogo.get("Vidrios").getImagen(),
                130,130);
        
        btnAtras.setIcon(atras);
        btnCarton.setIcon(carton);
        btnOrdinarios.setIcon(ordinarios);
        btnOrganicos.setIcon(organicos);
        btnPapel.setIcon(papel);
        btnPeligroso.setIcon(peligroso);
        btnPlastico.setIcon(plastico);
        btnVidrio.setIcon(vidrio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPlastico = new javax.swing.JButton();
        btnPapel = new javax.swing.JButton();
        btnOrdinarios = new javax.swing.JButton();
        btnOrganicos = new javax.swing.JButton();
        btnCarton = new javax.swing.JButton();
        btnVidrio = new javax.swing.JButton();
        btnPeligroso = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 255, 204));
        setPreferredSize(new java.awt.Dimension(370, 620));

        btnPlastico.setBackground(new java.awt.Color(184, 239, 255));
        btnPlastico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPlastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlasticoActionPerformed(evt);
            }
        });

        btnPapel.setBackground(new java.awt.Color(184, 239, 255));
        btnPapel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPapelActionPerformed(evt);
            }
        });

        btnOrdinarios.setBackground(new java.awt.Color(184, 239, 255));
        btnOrdinarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnOrdinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdinariosActionPerformed(evt);
            }
        });

        btnOrganicos.setBackground(new java.awt.Color(184, 239, 255));
        btnOrganicos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnOrganicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganicosActionPerformed(evt);
            }
        });

        btnCarton.setBackground(new java.awt.Color(184, 239, 255));
        btnCarton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCarton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartonActionPerformed(evt);
            }
        });

        btnVidrio.setBackground(new java.awt.Color(184, 239, 255));
        btnVidrio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnVidrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVidrioActionPerformed(evt);
            }
        });

        btnPeligroso.setBackground(new java.awt.Color(184, 239, 255));
        btnPeligroso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPeligroso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeligrosoActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 186, 68));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPeligroso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrdinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlastico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdinarios, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrganicos, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVidrio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPeligroso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        retroceder();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnPlasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlasticoActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Botellas plasticas, garrafas, "
                + "envases y tapas se deben introducir en los contenedores de"
                + " color azul. Recuerda lavarlos y secarlos  muy bien antes"
                + "de depositarlos.");
        Font fuente1= new Font("Berlin Sans FB", 0, 20);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cPlastico.png").getImage(),94,140));
        residuos.getLblSalud().setText("+"+String.valueOf(new Plasticos().getRecompensa())+" Salud");
        imagenResiduo = 1;
        
        revalidate();
        repaint();
        
    }//GEN-LAST:event_btnPlasticoActionPerformed

    private void btnPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPapelActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Papel de impresion, plegadizo, "
                + "periodico y carpetas van en los contenedores gris claro. "
                + "El papel debe estar limpio (sin restos de grasa principalmente"
                + ") y seco. Para ahorrar espacio es mejor que este doblado.");
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cPCarton.png").getImage(),94,140));
        Font fuente1= new Font("Berlin Sans FB", 0, 18);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblSalud().setText("+"+String.valueOf(new Papel().getRecompensa())+" Salud");
        imagenResiduo=2;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnPapelActionPerformed

    private void btnOrdinariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdinariosActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Todo lo que no entra en ninguna "
                + "otra categoria. Envoltorios de comida, huesos, servilletas, icopor, "
                + "desechables, etc, se introducen en el recipiente verde. Estos"
                + " residuos son muy contaminantes y terminan en rellenos sanita"
                + "rios. Reduce su consumo.");
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cOrdinario.png").getImage(),94,140));
        Font fuente1= new Font("Berlin Sans FB", 0, 17);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblSalud().setText("+"+String.valueOf(new Papel().getRecompensa())+" Salud");
        imagenResiduo=3;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnOrdinariosActionPerformed

    private void btnOrganicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganicosActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Restos de comida, cáscaras de frutas"
                + " y vegetales, residuos de jardinería y elementos de madera"
                + " pequeños como palillos y corchos se depositan en los recipientes"
                + " color beige o crema. Estos desechos se descomponen rápidamente"
                + " y se puede hacer compost con ellos :D");
        Font fuente1= new Font("Berlin Sans FB", 0, 17);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cOrganicos.png").getImage(),94,140));
        residuos.getLblSalud().setText("+"+String.valueOf(new Organicos().getRecompensa())+" Salud");
        imagenResiduo=4;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnOrganicosActionPerformed

    private void btnCartonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartonActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Cajas de embalaje, tetrapack, "
                + "cajas de leche o licores se introducen en los recipientes de"
                + "color gris claro. Los envases deben estar limpios y secos. "
                + "Para ahorrar espacio lo mas recomendable es desarmar las "
                + "cajas y tetrapacks.");
        Font fuente1= new Font("Berlin Sans FB", 0, 18);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cPCarton.png").getImage(),94,140));
        residuos.getLblSalud().setText("+"+String.valueOf(new Carton().getRecompensa())+" Salud");
        imagenResiduo=5;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnCartonActionPerformed

    private void btnVidrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVidrioActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("Botellas de vidrio de licores o "
                + "bebidas, frascos de colonia o cosmeticos  se depositan en con"
                + "tenedores de color blanco. Espejos, botellas y ventanas rotas"
                + " NO se incluyen aqui. Las botellas deben estar lipias, secas y"
                + " sin etiquetas.");
        Font fuente1= new Font("Berlin Sans FB", 0, 18);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cVidrio.png").getImage(),94,140));
        residuos.getLblSalud().setText("+"+String.valueOf(new Vidrios().getRecompensa())+" Salud");
        imagenResiduo=6;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnVidrioActionPerformed

    private void btnPeligrosoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeligrosoActionPerformed
        PantallaDescripcionResiduos residuos = new PantallaDescripcionResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        this.removeAll();
        add(residuos,BorderLayout.CENTER);
        residuos.getLblDescripcion().setText("baterias, bombillas, aparatos "
                + "electronicos, aerosoles, solventes, aceites, tienen un manejo"
                + " especial. Nunca deben mezclarse entre si y deben llevarse a"
                + " puntos autorizados para su correcto manejo.");
        Font fuente1= new Font("Berlin Sans FB", 0, 19);
                residuos.getLblDescripcion().setFont(fuente1);
        residuos.getLblImagen().setIcon(Pantalla.escalar(new ImageIcon("./src/img/"
                + "cPeligrosos.png").getImage(),94,140));
        residuos.getLblSalud().setText("+"+String.valueOf(new Peligrosos().getRecompensa())+" Salud");
        imagenResiduo=7;
        
        revalidate();
        repaint();
    }//GEN-LAST:event_btnPeligrosoActionPerformed
    
    public void retroceder(){
        Gato gato = new Gato();
        PantallaInicio pantallaInicio = new PantallaInicio(true,gato);
        pantallaInicio.getjPanel1().setSize(370,620);
        pantallaInicio.getjPanel1().setLocation(0, 0);
        removeAll();
        add(pantallaInicio.getjPanel1(),BorderLayout.CENTER);
        gato.getT().start();
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCarton;
    private javax.swing.JButton btnOrdinarios;
    private javax.swing.JButton btnOrganicos;
    private javax.swing.JButton btnPapel;
    private javax.swing.JButton btnPeligroso;
    private javax.swing.JButton btnPlastico;
    private javax.swing.JButton btnVidrio;
    // End of variables declaration//GEN-END:variables

    public static int getImagenResiduo() {
        return imagenResiduo;
    }

    public static void setImagenResiduo(int imagenResiduo) {
        PantallaDeResiduos.imagenResiduo = imagenResiduo;
    }

    
}
