/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.Gato;
import java.awt.BorderLayout;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextPane;

/**
 *
 * @author TOSHIBA
 */
public class PantallaDescripcionResiduos extends javax.swing.JPanel implements Serializable{
    private static boolean caida=false;
    public PantallaDescripcionResiduos() {
        initComponents();
        ImageIcon atras = Pantalla.escalar(new ImageIcon("./src/img/atras.png").
                getImage(), 40, 40);
        ImageIcon ok =  Pantalla.escalar(new ImageIcon("./src/img/ok.png").
                getImage(), 40, 40);
        ImageIcon cancelar =  Pantalla.escalar(new ImageIcon("./src/img/cancelar."
                + "png").getImage(), 40, 40);
        
        btnAtras.setIcon(atras);
        btnOk.setIcon(ok);
        btnCancelar.setIcon(cancelar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextPane();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(238, 255, 204));
        setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N

        btnOk.setBackground(new java.awt.Color(255, 186, 68));
        btnOk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(255, 186, 68));
        btnAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        lblImagen.setBackground(new java.awt.Color(255, 255, 255));
        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblSalud.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        lblSalud.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblDescripcion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        lblDescripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        lblDescripcion.setEnabled(false);
        lblDescripcion.setMargin(new java.awt.Insets(3, 5, 3, 3));
        jScrollPane1.setViewportView(lblDescripcion);

        btnCancelar.setBackground(new java.awt.Color(255, 186, 68));
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Gato gato = new Gato();
        PantallaInicio pantallaInicio = new PantallaInicio(true,gato);
        PantallaDescripcionResiduos.setCaida(true);
        pantallaInicio.getjPanel1().setSize(370,620);
        pantallaInicio.getjPanel1().setLocation(0,0);
        removeAll();
        PantallaInicio.getjLabel1().setVisible(true);
        add(pantallaInicio.getjPanel1(),BorderLayout.CENTER);
        switch(PantallaDeResiduos.getImagenResiduo()){
                case 1:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Plasticos").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Plasticos"));
                    break;
                case 2:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Papel").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Papel"));
                    break;
                case 3:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Ordinarios").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Ordinarios"));
                    break;
                case 4:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Organicos").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Organicos"));
                    break;
                case 5:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Carton").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Carton"));
                    break;
                case 6:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Vidrios").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Vidrios"));
                    break;
                case 7:
                    PantallaInicio.getjLabel1().setIcon(Pantalla.escalar(
                    PantallaDeResiduos.catalogo.get("Peligrosos").getImagen(),80, 80));
                    gato.comer(PantallaDeResiduos.catalogo.get("Peligrosos"));
                    break;
            }
        gato.getT().start();
        revalidate();
        repaint();   

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        retroceder();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        salir();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
    public void salir(){
        Gato gato = new Gato();
        PantallaInicio pantallaInicio = new PantallaInicio(true,gato);
        pantallaInicio.getjPanel1().setSize(370,620);
        pantallaInicio.getjPanel1().setLocation(0, 0);
        removeAll();
        add(pantallaInicio.getjPanel1(),BorderLayout.CENTER);
        gato.getT().start();
        revalidate();
        repaint();
    }
    
    public void retroceder(){
        PantallaDeResiduos residuos = new PantallaDeResiduos();
        residuos.setSize(370,620);
        residuos.setLocation(0, 0);
        removeAll();
        add(residuos,BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane lblDescripcion;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblSalud;
    // End of variables declaration//GEN-END:variables


    public JLabel getLblImagen() {
        return lblImagen;
    }

    public void setLblImagen(JLabel lblImagen) {
        this.lblImagen = lblImagen;
    }

    public JLabel getLblSalud() {
        return lblSalud;
    }

    public void setLblSalud(JLabel lblSalud) {
        this.lblSalud = lblSalud;
    }

    public JTextPane getLblDescripcion() {
        return lblDescripcion;
    }

    public void setLblDescripcion(JTextPane lblDescripcion) {
        this.lblDescripcion = lblDescripcion;
    }
    
    public static boolean isCaida() {
        return caida;
    }

    public static void setCaida(boolean caida) {
        PantallaDescripcionResiduos.caida = caida;
    }
    
    
}
