/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.Gato;
import java.awt.BorderLayout;
import java.awt.Font;
import javax.swing.ImageIcon;

/**
 *
 * @author TOSHIBA
 */
public class PantallaTutorialReciclaje extends javax.swing.JPanel {

    private int slide;
    
    ImageIcon espacio = Pantalla.escalar(new ImageIcon("./src/img/espacio.jpg").
                getImage(), 170, 130);
        ImageIcon recipientes = Pantalla.escalar(new ImageIcon("./src/img/recipientes.jpg").
                getImage(), 170, 130);
        ImageIcon bolsas = Pantalla.escalar(new ImageIcon("./src/img/bolsas.jpg").
                getImage(), 170, 130);
        ImageIcon consultar = Pantalla.escalar(new ImageIcon("./src/img/consultar.jpg").
                getImage(), 170, 130);
        ImageIcon reducir = Pantalla.escalar(new ImageIcon("./src/img/reducir.png").
                getImage(), 170, 130);
    
    public PantallaTutorialReciclaje() {
        initComponents();
        slide=0;
        ImageIcon atras = Pantalla.escalar(new ImageIcon("./src/img/atras.png").
                getImage(), 40, 40);
        ImageIcon anterior = Pantalla.escalar(new ImageIcon("./src/img/anterior.png").
                getImage(), 40, 40);
        ImageIcon adelante = Pantalla.escalar(new ImageIcon("./src/img/adelante.png").
                getImage(), 40, 40);

        bntAtras.setIcon(atras);
        btnAdelante.setIcon(adelante);
        btnAnterior.setIcon(anterior);
        btnAnterior.setEnabled(false);

        colocarImagen(slide);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntAtras = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnAdelante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(238, 255, 204));

        bntAtras.setBackground(new java.awt.Color(255, 186, 68));
        bntAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        bntAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtrasActionPerformed(evt);
            }
        });

        btnAnterior.setBackground(new java.awt.Color(255, 186, 68));
        btnAnterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnAdelante.setBackground(new java.awt.Color(255, 186, 68));
        btnAdelante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdelanteActionPerformed(evt);
            }
        });

        jTextPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        jTextPane1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jTextPane1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextPane1.setEnabled(false);
        jTextPane1.setMargin(new java.awt.Insets(5, 10, 5, 5));
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(bntAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(bntAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtrasActionPerformed
        retroceder();
    }//GEN-LAST:event_bntAtrasActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(slide==4){
            slide--;
            btnAdelante.setEnabled(true);
        }else if (slide == 1) {
            slide--;
            btnAnterior.setEnabled(false);
        }else{
            slide--;
        }
        colocarImagen(slide);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdelanteActionPerformed
        if(slide==0){
            slide++;
            btnAnterior.setEnabled(true);
        }else if (slide == 3) {
            slide++;
            btnAdelante.setEnabled(false);
        }else{
            slide++;
        }
        colocarImagen(slide);
    }//GEN-LAST:event_btnAdelanteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAtras;
    private javax.swing.JButton btnAdelante;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

    public void retroceder(){
        Gato gato = new Gato();
        PantallaInicio pantallaInicio = new PantallaInicio(true,gato);
        pantallaInicio.getjPanel1().setSize(370,620);
        pantallaInicio.getjPanel1().setLocation(0, 0);
        removeAll();
        add(pantallaInicio.getjPanel1(),BorderLayout.CENTER);
        gato.getT().start();
        revalidate();
        repaint();
    }

    public int getSlide() {
        return slide;
    }

    public void setSlide(int slide) {
        this.slide = slide;
    }
    
    public void colocarImagen(int i){
        switch(i){
            case 0:
                jTextPane1.setText("Busca un espacio adecuado para colocar los "
                        + "cubos o  bolsas.Este debe ser lo suficientemente grande"
                        + " para que no estorbe. Lugares ideales puden ser la cocina"
                        + ", la despensa o el patio.");
                Font fuente1= new Font("Berlin Sans FB", 0, 18);
                jTextPane1.setFont(fuente1);
                jLabel1.setIcon(espacio);
                break;
            case 1:
                jTextPane1.setText("Dispon de recipientes de diferentes colores o"
                        + " etiquetas donde puedas hacer la separacion de tus residuos"
                        + ". No es necesario tener todos los tipos  de recipientes, "
                        + "pero mientras mejor clasificados queden tus residuos, mejor!");
                Font fuente2= new Font("Berlin Sans FB", 0, 18);
                jTextPane1.setFont(fuente2);
                jLabel1.setIcon(recipientes);
                break;
            case 2:
                jTextPane1.setText("Es recomendable colocar bolsas dentro de tus"
                        + " contenedores para facilitar su mantenimiento y la manipulación de los "
                        + "residuos. Usa bolsas azules para plástico, vidrio, metales y multicapa;"
                        + " verdes para organicos y grises para papel y carton.");
                jLabel1.setIcon(bolsas);
                Font fuente3= new Font("Berlin Sans FB", 0, 17);
                jTextPane1.setFont(fuente3);
                break;
            case 3:
                jTextPane1.setText("En caso de  que  tengas alguna  duda sobre como"
                        + " separar tus residuos no dudes en consultar. Para eso"
                        + " estamos nosotros :D");
                jLabel1.setIcon(consultar);
                Font fuente4= new Font("Berlin Sans FB", 0, 20);
                jTextPane1.setFont(fuente4);
                break;
            case 4:
                jTextPane1.setText("¡Sigue la regla  de las 3 R's: Reusar, reutilizar"
                        + " y reciclar! Disminuye el consumo de productos desechables y "
                        + "plasticos y evita el uso de artículos innecesarios. ¡A los pitillos "
                        + "diles NO!");
                jLabel1.setIcon(reducir);
                Font fuente5= new Font("Berlin Sans FB", 0, 19);
                jTextPane1.setFont(fuente5);
                break;
        }
    }

}
