/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.Gato;
import datos.Personaje;
import java.awt.BorderLayout;
import java.io.Serializable;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
/**
 *
 * @author TOSHIBA
 */
public class PantallaInicio extends javax.swing.JFrame implements Runnable, Serializable{
    
    private Gato gatito; 
    private boolean menu=true;
    
    public PantallaInicio(boolean movimiento, Gato gatito) {
        initComponents();
        setLocationRelativeTo(null);
        this.gatito=gatito;
        gatito.setMovimiento(movimiento);
        
        ImageIcon comer = new ImageIcon("./src/img/comer.png");
        comer = Pantalla.escalar(comer.getImage(), 40,40);
        ImageIcon tienda = new ImageIcon("./src/img/tienda.png");
        tienda = Pantalla.escalar(tienda.getImage(), 40,40);
        ImageIcon ajustes = new ImageIcon("./src/img/ajustes.png");
        ajustes = Pantalla.escalar(ajustes.getImage(), 40,40);
        ImageIcon menu = new ImageIcon("./src/img/menu.png");
        menu = Pantalla.escalar(menu.getImage(), 35,35);
        ImageIcon dinero = new ImageIcon("./src/img/dinero.png");
        dinero = Pantalla.escalar(dinero.getImage(), 50,50);
        ImageIcon salud = new ImageIcon("./src/img/salud.png");
        salud = Pantalla.escalar(salud.getImage(), 40,40);

        Fondo im = new Fondo(jPanel1,"fondo");
        jPanel1.add(im).repaint();
        
        setTitle("ReciCat");
        setIconImage (new ImageIcon("./src/img/logo.png").getImage());
        
        lblDinero.setHorizontalAlignment(JLabel.CENTER);
        lblDinero.setVerticalAlignment(JLabel.CENTER);
        lblSalud.setHorizontalAlignment(JLabel.CENTER);
        lblSalud.setVerticalAlignment(JLabel.CENTER);
        Pantalla.volverTransparente(btnGato);
        btnAjustes.setIcon(ajustes);
        btnComida.setIcon(comer);
        btnMenu.setIcon(menu);
        btnTienda.setIcon(tienda);
        lblDinero.setIcon(dinero);
        lblSalud.setIcon(salud);
        jLabel1.setVisible(false);
        txtDinero.setText(Integer.toString(Personaje.cargarDinero()));     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAjustes = new javax.swing.JButton();
        btnComida = new javax.swing.JButton();
        btnTienda = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jProgressBar2 = new javax.swing.JProgressBar();
        lblDinero = new javax.swing.JLabel();
        lblSalud = new javax.swing.JLabel();
        btnGato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDinero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(370, 620));

        jPanel1.setPreferredSize(new java.awt.Dimension(370, 620));

        btnAjustes.setBackground(new java.awt.Color(255, 186, 68));
        btnAjustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });

        btnComida.setBackground(new java.awt.Color(255, 186, 68));
        btnComida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComidaActionPerformed(evt);
            }
        });

        btnTienda.setBackground(new java.awt.Color(255, 186, 68));
        btnTienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiendaActionPerformed(evt);
            }
        });

        btnMenu.setBackground(new java.awt.Color(255, 186, 68));
        btnMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jProgressBar2.setForeground(new java.awt.Color(255, 0, 0));
        jProgressBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblDinero.setBackground(new java.awt.Color(255, 255, 0));

        lblSalud.setBackground(new java.awt.Color(255, 0, 0));
        lblSalud.setToolTipText("");

        btnGato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGatoActionPerformed(evt);
            }
        });

        txtDinero.setBackground(new java.awt.Color(51, 255, 0));
        txtDinero.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        txtDinero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtDinero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtDinero.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGato, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(122, 122, 122)
                .addComponent(btnGato, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjustes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComida, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        gatito.setMovimiento(false);
        Menu menu = new Menu();
        menu.setSize(370,620);
        menu.setLocation(0, 0);
        jPanel1.removeAll();
        jPanel1.add(menu, BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();

    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComidaActionPerformed
        if (gatito.getSalud() <= 80) {
            gatito.setMovimiento(false);
            t.interrupt();
            PantallaDeResiduos pantallaDeResiduos = new PantallaDeResiduos();
            pantallaDeResiduos.setSize(370, 620);
            pantallaDeResiduos.setLocation(0, 0);
            jPanel1.removeAll();
            jPanel1.add(pantallaDeResiduos, BorderLayout.CENTER);
            jPanel1.revalidate();
            jPanel1.repaint();
        } else {
            JOptionPane.showMessageDialog(this, "No me alimentes más por el "
                    + "momento o me dará  dolor de pancita!", "Estoy lleno!!!",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnComidaActionPerformed

    private void btnTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiendaActionPerformed
        gatito.setMovimiento(false);
        PantallaAccesorios accesorios = new PantallaAccesorios();
        accesorios.setSize(370,620);
        accesorios.setLocation(0,0);
        jPanel1.removeAll();
        jPanel1.add(accesorios,BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnTiendaActionPerformed

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        gatito.setMovimiento(false);
        PantallaAjustes ajustes =  new PantallaAjustes();
        ajustes.setSize(370,620);
        ajustes.setLocation(0,0);
        jPanel1.removeAll();
        jPanel1.add(ajustes,BorderLayout.CENTER);
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnGatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGatoActionPerformed
        gatito.setMovimiento(false);
        gatito.getT().suspend();
        Gato gato = new Gato();
        gatito = gato; 
        gatito.setMirar(true);
        gatito.setMovimiento(true);
        gatito.getT().start();
        
    }//GEN-LAST:event_btnGatoActionPerformed
    private Thread t = new Thread(this); 
    
    @Override
    public void run() {
        gatito.getT().start();
            new PantallaInicio(true,gatito).setVisible(true);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnComida;
    private static javax.swing.JButton btnGato;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTienda;
    private static javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JLabel lblDinero;
    private javax.swing.JLabel lblSalud;
    private static javax.swing.JLabel txtDinero;
    // End of variables declaration//GEN-END:variables

    public Thread getT() {
        return t;
    }

    public void setT(Thread t) {
        this.t = t;
    }

    public Gato getGatito() {
        return gatito;
    }

    public void setGatito(Gato gatito) {
        this.gatito = gatito;
    }

    public static JButton getBtnGato() {
        return btnGato;
    }

    public static void setBtnGato(JButton btnGato) {
        PantallaInicio.btnGato = btnGato;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public static JLabel getjLabel1() {
        return jLabel1;
    }

    public static void setjLabel1(JLabel jLabel1) {
        PantallaInicio.jLabel1 = jLabel1;
    }

    public static JProgressBar getjProgressBar2() {
        return jProgressBar2;
    }

    public static void setjProgressBar2(JProgressBar jProgressBar2) {
        PantallaInicio.jProgressBar2 = jProgressBar2;
    }

    public static JLabel getTxtDinero() {
        return txtDinero;
    }

    public static void setTxtDinero(JLabel txtDinero) {
        PantallaInicio.txtDinero = txtDinero;
    }

}
